#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
conda install -c bioconda fastq-join
# setting temporary directory
export TMPDIR=~/qiime_tmp
# join reads
echo "Joining reads"
time join_paired_ends.py -f Read1.fastq.gz -r Read2.fastq.gz -o ./joined -b Index.fastq.gz
# deactivating environment
source deactivate
