#!/bin/bash

#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# compare alpha diversity between samples
echo "Alpha diversity comparison"
time compare_alpha_diversity.py -i cdout_silva_3/arare_max640/alpha_div_collated/PD_whole_tree.txt -o alpha_comparisons/ -m map_expo.tsv 
-c SamplePh,SampleNitrogen,SamplePotassium,SampleDepth,SamplePhosphorus -t nonparametric -n 9999 -d 640
source deactivate
