#!/bin/bash

#SBATCH -t 1:00:00
#SBATCH -n 16
#SBATCH -p short
#Load modules to run python
module load eb
module load Miniconda2
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# summarize taxa in OTU biom table
echo "Summarizing taxa"
time summarize_taxa.py -i ./otus_closed_silva/otu_table.biom -o taxa_summary_silva
source deactivate
